# =============================================================================
# jsonette — GitHub Actions CI
#
# Pipeline: Build - Test - Clippy - fmt
#
# No required GitHub Actions secrets.
# =============================================================================


name: Engine

on:
  pull_requests:
    branches: [main]
  push:
    branches: [main]
    tags: ['v*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -------------------------------------------------------------------------- #
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: dtolnay/rust-toolchain@stable
        run: cargo build --workspace
        working-directory: ./engine

  # -------------------------------------------------------------------------- #
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        uses: dtolnay/rust-toolchain@stable
        run: cargo test --workspace
        working-directory: ./engine
  
  # -------------------------------------------------------------------------- #
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clippy
        uses: dtolnay/rust-toolchain@stable
        run: cargo clippy -- -D warnings
        working-directory: ./engine

  # -------------------------------------------------------------------------- #
  Fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fmt
        uses: dtolnay/rust-toolchain@stable
        run: cargo fmt --checkout
        working-directory: ./engine

